/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#a9bad3",
        "secondary-container": "#3a4a5f",
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-fixed": "#00174b",
        "on-tertiary": "#581e00",
        surface: "#11131b",
        "tertiary-container": "#bc4800",
        "surface-container-lowest": "#0c0e16",
        "tertiary-fixed": "#ffdbcd",
        "surface-container-high": "#282a32",
        "error-container": "#93000a",
        "surface-container": "#1d1f27",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-variant": "#32343d",
        "on-error": "#690005",
        "on-surface-variant": "#c3c6d7",
        outline: "#8d90a0",
        "on-tertiary-fixed": "#360f00",
        "primary-fixed": "#dbe1ff",
        "on-secondary": "#213145",
        "on-background": "#e1e2ed",
        "primary-container": "#2563eb",
        tertiary: "#ffb596",
        "secondary-fixed": "#d3e4fe",
        "surface-container-low": "#191b23",
        background: "#11131b",
        "on-primary-container": "#eeefff",
        "surface-bright": "#373942",
        "on-surface": "#e1e2ed",
        "inverse-on-surface": "#2e3039",
        "surface-container-highest": "#32343d",
        "inverse-primary": "#0053db",
        "on-primary-fixed-variant": "#003ea8",
        "on-error-container": "#ffdad6",
        "surface-dim": "#11131b",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#b7c8e1",
        primary: "#b4c5ff",
        "inverse-surface": "#e1e2ed",
        "on-tertiary-container": "#ffede6",
        "surface-tint": "#b4c5ff",
        "on-primary": "#002a78",
        "outline-variant": "#434655",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed-dim": "#ffb596",
        secondary: "#b7c8e1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        "container-max": "1280px",
        "2xl": "48px",
        gutter: "24px",
        base: "8px",
        xs: "4px",
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        display: ["Inter"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        display: [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
  plugins: [],
};
