services:
  teampilot-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teampilot-spring-backend
    ports:
      # Maps the host's HTTP port (8080) to container app port (1818)
      - "8080:1818"
    env_file:
      - .env
    
    volumes:
      # Mounts your Kafka ca.pem file into the container
      # Left side: Path on your host machine (EC2 or Local)
      # Right side: Path inside the Docker container
      - ./certs/ca.pem:/app/certs/ca.pem:ro
      
      # Mounts a persistent volume for document storage so files survive restarts
      - teampilot-documents:/app/storage/documents
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Define the persistent volume for documents
volumes:
  teampilot-documents: